apiVersion: v1
kind: Service
metadata:
  name: my-gpu-service
spec:
  selector:
    app: my-gpu-app # This should match a label in your Pod's metadata
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80 # The port that the service will serve on
    targetPort: 5000 # The target port on the container
